<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <InfoBox statusType="info">
      <h5>お問い合わせありがとうございます。</h5>
      <p>お送り頂きました内容を確認の上、必要に応じて折り返しご連絡させて頂きます。</p>
      <p>また、ご記入頂いたメールアドレスへ、自動返信の確認メールをお送りしております。</p>
      <p>
        しばらく経ってもメールが届かない場合は、入力頂いたメールアドレスが間違っているか、迷惑メールフォルダに振り分けられている可能性がございます。
      </p>
      <p>
        ドメイン指定をされている場合は、「@voidhacker.com」からのメールが受信できるよう予め設定をお願いいたします。
        以上の内容をご確認の上、お手数ですがもう一度フォームよりお問い合わせ頂きますようお願い申し上げます。
      </p>

      なお、お急ぎの場合は電話でもご相談を受け付けております。 090-6281-6335までご遠慮なくご相談ください。
    </InfoBox>
  </article>
</Post>
