<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  let name: string = '';
  let email: string = '';
  let message: string = '';
  let isSubmitted: boolean = false;

  $: isNameError = name.trim() === '';
  $: isMessageError = message.trim() === '';
  $: isEmailError = !/[\w\-._]+@[\w\-._]+\.[A-Za-z]+/.test(email);
  $: isValid = isNameError === isMessageError && isNameError === isEmailError && isEmailError === false;

  function handleSubmit(event: any) {
    event.preventDefault();
    isSubmitted = true;
    if (!isValid) return;
    const form = event.target;
    const formData = new FormData(form);
    fetch(form.action, {
      method: form.method,
      body: formData,
    })
      .then((res) => {
        if (res.ok) {
          // POSTに成功した場合の処理
          window.location.href = './Contact/thanks';
        } else {
          // POSTに失敗した場合の処理
          console.error('POST failed', res);
          //TODO:Reset form and Error Modal
          window.location.href = './Contact/thanks';
        }
      })
      .catch((error) => {
        // POST時にエラーが発生した場合の処理
        console.error('POST failed', error);
        window.location.href = './Contact/thanks';
        //TODO:Reset form and Error Modal
      });
  }
</script>

<svelte:head><title>お問い合わせ | VoidHack</title></svelte:head>

<Post>
  <article slot="post_content">
    <form
      on:submit={handleSubmit}
      id="form"
      action="https://docs.google.com/forms/u/0/d/e/1FAIpQLSe5Rmt9_mnAFJyiVIAZ67RDRrQ98UwCGnr_6elpToY9xj7sJw/formResponse"
      method="POST"
      novalidate>
      <div class="item">
        <label class="form-label" for="name">お名前</label>
        <input
          class="form-control"
          type="text"
          name="entry.389510866"
          id="name"
          placeholder="Yasura Huzino"
          bind:value={name}
          required />
        {#if isSubmitted}
          {#if isNameError}
            <InfoBox statusType="error"><p>名前を入力してください。</p></InfoBox>
          {/if}
        {/if}
      </div>
      <div class="item">
        <label class="form-label" for="email">メールアドレス</label>
        <input
          class="form-control"
          type="email"
          name="entry.1502175313"
          placeholder="xxx@example.com"
          id="email"
          bind:value={email}
          required />
        {#if isSubmitted}
          {#if isEmailError}
            <InfoBox statusType="error"><p>正しいメールアドレスを入力してください。</p></InfoBox>
          {/if}
        {/if}
      </div>

      <div class="item">
        <label class="form-label" for="input_ex">お問い合わせ・ご意見</label>
        <textarea
          class="form-control"
          id="input_ex"
          name="entry.1364742016"
          placeholder="お友達になってくれませんか？"
          bind:value={message}
          required />
        {#if isSubmitted}
          {#if isMessageError}
            <InfoBox statusType="error"><p>問い合わせ内容を入力してください。</p></InfoBox>
          {/if}
        {/if}
      </div>
      <input type="submit" />
    </form>
  </article>
</Post>

<style>
  .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + 0.75rem + 2px);
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
  }

  .form-control:focus {
    color: #495057;
    background-color: #fff;
    border-color: #80bdff;
    outline: 0;
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
  }

  .form-label {
    font-weight: 700;
    margin-bottom: 0.5rem;
  }

  textarea.form-control {
    display: block;
    width: 100%;
    height: 150px;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
  }

  input[type='submit'] {
    background-color: #4caf50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    width: 80px;
  }

  input:disabled {
    background-color: #495057;
  }
</style>
