<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Folder from '$lib/components/folder.svelte';
  const oldDir = [
    { name: 'デスクトップ' },
    { name: 'ドキュメント' },
    { name: 'ダウンロード' },
    { name: 'ミュージック' },
    { name: 'テンプレート' },
    { name: 'ビデオ' },
  ];
  const newDir = [
    { name: 'Desktop' },
    { name: 'Documents' },
    { name: 'Downloads' },
    { name: 'Music' },
    { name: 'Templates' },
    { name: 'Videos' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h1 id="hajimeni"><a href="#hajimeni">✨はじめに</a></h1>
    <p>
      Linuxを日本語インストールしてあるあるなのが、ホームディレクトリだけが
      <code class="inline-code-block">ダウンロード</code>
      だったり
      <code class="inline-code-block">デスクトップ</code>
      だったりするアレです。
    </p>
    <p>個人的に下記のやらかしをするのでセットアップ時は気をつけようと思います。</p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token builtin class-name">cd</span> Desktop</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">cd: そのようなファイルやディレクトリはありません: Desktop</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>今回のイメージ図</p>
    <div style="display:flex;justify-content:space-around;">
      <Folder name="設定前" files={oldDir} expanded />
      <Folder name="設定後" files={newDir} expanded />
    </div>

    <h1 id="huan2-jing4"><a href="#huan2-jing4">💻環境</a></h1>
    <p>端末:Apple Inc. MacBookAir7,2</p>
    <p>OS:Pop!_OS 22.04 LTS x64</p>
    <p>X Window System:X11</p>
    <p>GNOME:42.5</p>
    <p>shell:zsh 5.8.1(gnome-terminal)</p>
    <h1 id="insutru"><a href="#insutru">⚡インストール</a></h1>
    <InfoBox statusType="info"><p>GNOME等は最初から導入されているのでこの手順はスキップして構いません。</p></InfoBox>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">sudo</span> <span class="token function">apt</span> <span class="token function">install</span> xdg-user-dirs</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h1 id="direkutorino"><a href="#direkutorino">🔨ディレクトリの作成</a></h1>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token assign-left variable"><span class="token environment constant">LC_ALL</span></span><span class="token operator">=</span>C xdg-user-dirs-update <span class="token parameter variable">--force</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <InfoBox statusType="info">
      <p>ローカライズされたディレクトリを作成するには下記で作成出来ます。</p>
      <div class="code-block">
        <CodeCopy>
          <pre><code
              class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">xdg-user-dirs-update</div></div>`}</code></pre>
        </CodeCopy>
      </div>
    </InfoBox>
    <p>
      問題なく作成されているか確認するには
      <code class="inline-code-block">ls</code>
      コマンド等を使用して確認しましょう。
    </p>
    <InfoBox statusType="tip">
      <p>
        カスタムディレクトリを作成することも可能です。 下記は公開フォルダを
        <code class="inline-code-block">Shared</code>
        というフォルダにバインドする例です。
      </p>
      <div class="code-block">
        <CodeCopy>
          <pre><code
              class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">xdg-user-dirs-update <span class="token parameter variable">--set</span> PUBLICSHARE ~/Shared</div></div>`}</code></pre>
        </CodeCopy>
      </div>
    </InfoBox>
    <h1 id="matome"><a href="#matome">📕まとめ</a></h1>
    <p>案外簡単に変更出来て拍子抜けしました。</p>
    <p>カスタムフォルダは個人的に重宝しています。</p>
    <p>
      ちなみに
      <code class="inline-code-block">LC_ALL=C</code>
      というのはロケール環境変数
      <code class="inline-code-block">LC_ALL</code>
      に代入をし、
    </p>
    <p>一時的にアメリカ英語ロケールに切り替えるために使用しています。</p>
  </article>
</Post>
