<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="gai4-yao4"><a href="#gai4-yao4">概要</a></h2>
    <p>
      このブログは
      <a href="https://twitter.com/const_root/" rel="external">あると</a>
      が気ままにつぶやく技術系(？)ブログです
    </p>
    <h2 id="konohmupjidetteirumono"><a href="#konohmupjidetteirumono">✨このホームページで使っているもの</a></h2>
    <p>下記に使わせている技術などを記載しております。</p>
    <ul>
      <li>
        ⚡
        <a href="https://kit.svelte.jp/" rel="external">Svelte Kit</a>
      </li>
    </ul>
    <p>SvelteとViteを組み合わせたフレームワークで、非常に簡潔に記述出来ます。</p>
    <ul>
      <li>
        🤗 <a href="https://github.com/kwchang0831/svelte-QWER" rel="external">svelte-QWER</a>
      </li>
    </ul>
    <p>
      <a href="https://kit.svelte.jp/" rel="external">Svelte Kit</a>
      上で非常に高速で動作するブログスターターキットです。
    </p>
    <ul>
      <li>💎 giscus</li>
    </ul>
    <p>
      <a href="https://docs.github.com/en/discussions" rel="external">GitHub Discussions</a>
      を利用したコメントシステムです。
    </p>
    <h2 id="raisensu"><a href="#raisensu">📝 ライセンス</a></h2>
    <p><a href="https://github.com/Nich87/VoidHack/blob/main/LICENSE" rel="external">MIT</a></p>
  </article>
</Post>
