<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="hajimeni"><a href="#hajimeni">✨ はじめに</a></h2>
    <InfoBox statusType="caution">
      <p>TwiFucker並びにLSPatchを導入したことによる故障、アカウントBANについては責任を負いかねます。</p>
    </InfoBox>
    <ol>
      <li>バッテリーを30%以上充電しましょう。</li>
      <li>バックアップを必ず行いましょう。</li>
    </ol>
    <h3 id="notesuto"><a href="#notesuto">🎉 今回のテスト環境</a></h3>
    <ul>
      <li>Pixal7 Pro(Android13)</li>
      <li>Twitter 9.64.0-release.0</li>
      <li><a href="https://github.com/LSPosed/LSPatch/releases" rel="external">LSPatch 0.5.1</a></li>
      <li><a href="https://github.com/Dr-TSNG/TwiFucker/releases" rel="external">TwiFucker v1.9</a></li>
    </ul>
    <h2 id="twifuckerwosu"><a href="#twifuckerwosu">⚡️ TwiFuckerを試す</a></h2>
    <ol>
      <li><h4 id="daunrdo"><a href="#daunrdo">各種ダウンロード</a></h4></li>
    </ol>
    <ul>
      <li><p><a href="https://github.com/LSPosed/LSPatch/releases" rel="external">LSPatch</a></p></li>
      <li>
        <p><a href="https://github.com/Dr-TSNG/TwiFucker/releases/tag/1.9" rel="external">TwiFucker</a></p>
        <p>ダウンロードしたらインストールを行いましょう。</p>
      </li>
    </ul>
    <ol>
      <li>
        <h4 id="patchiwoteru"><a href="#patchiwoteru">パッチを当てる</a></h4>
        <p>
          LSPatchを起動し、左から2番目の管理画面を開き、右下の
          <code class="inline-code-block">+</code>
          ボタンをタッチしてください。
        </p>
        <InfoBox statusType="tip">
          <p>パッチを適用する際はapkもしくはインストール済みのどちらかからで選択可能です。</p>
        </InfoBox>
      </li>
      <li>
        <h4 id="patchimdowosuru"><a href="#patchimdowosuru">パッチモードを選択する</a></h4>
        <p>
          そうすると下記のような画面が出てきますのでモード
          <strong>のみ</strong>
          選択しましょう。
        </p>
        <p>
          <ImgZoom
            src="Z:\202202\twifucker-install\assets\patchmode.png"
            alt="scrreenshot"
            width="1427"
            height="2908" />
        </p>
        <InfoBox statusType="tip">
          <ul>
            <li>
              <p>ローカルモード</p>
              <p>モジュールを内臓せずにLSPatchをバックグラウンドで動作させる。</p>
              <p>メリットとしてはモジュールのバージョンアップに再インストール無しで対応可能。</p>
            </li>
            <li>
              <p>ポータブルモード</p>
              <p>apk自体にモジュールを埋め込む。</p>
              <p>
                動的にバージョン管理が出来なくなるが、apk単体で動作するため他端末でも動作が可能になるメリットがあります。
              </p>
            </li>
          </ul>
        </InfoBox>
        <p>
          選択したら右下の
          <code class="inline-code-block">パッチを開始</code>
          ボタンをタップするとビルドが開始されます。
        </p>
      </li>
      <li>
        <h4 id="insutrusuru"><a href="#insutrusuru">インストールする</a></h4>
        <p>
          ビルド完了後に起動時に設定したディレクトリにビルド済みのapkがデプロイされます。
          <ImgZoom src="Z:\202202\twifucker-install\assets\build-apk.png" alt="scrennshot" width="1440" height="345" />
          インストールしたら再度LSPatchを起動し管理画面に行くと下記のように表示されているはずです。
        </p>
        <p>
          Twitterをタッチ→モジュールのスコープをタッチ
          <ImgZoom src="Z:\202202\twifucker-install\assets\kanri.png" alt="screenshot" width="1440" height="1140" />
        </p>
        <p>そうすると下記のようにTwiFuckerが出てくるので☑にします。</p>
        <p>
          完了したら、右下のボタンを押下し適用させてください。
          <ImgZoom src="Z:\202202\twifucker-install\assets\scope.png" alt="screenshot" width="1440" height="452" />
        </p>
      </li>
    </ol>
    <h2 id="natwitterraifuwo"><a href="#natwitterraifuwo">🚀 快適なTwitterライフを</a></h2>
    <p>起動した際にTwiFuckerのトーストが表示されていれば無事導入されています。</p>
    <p>
      <code class="inline-code-block">設定とプライバシー</code>
      =&gt;
      <code class="inline-code-block">その他のリソース</code>
      =&gt;
      <code class="inline-code-block">バージョンx.xx.x-xxx.x</code>
      の順に辿ると下記のようなモーダルが表示されるはずです。
    </p>
    <p>
      <ImgZoom src="Z:\202202\twifucker-install\assets\twifucker.png" alt="screenshot" width="1254" height="2793" />
    </p>
    <p>
      様々な項目がありますが大きな項目としては下記のようなドロワーアイテムの削除であったり、
      動画や画像のダウンロード機能などでしょうか。広告消去が一番大きなものではあると思います。
      <ImgZoom src="Z:\202202\twifucker-install\assets\twifk_menu.png" alt="screenshot" width="1246" height="1414" />
    </p>
    <h2 id="ji1-neng2-yi1-lan3"><a href="#ji1-neng2-yi1-lan3">📚 機能一覧</a></h2>
    <p>
      ここに主な機能とプレビュー画像が乗っています: <a
        href="https://github.com/Dr-TSNG/TwiFucker/blob/master/FEATURES.md"
        rel="external">
        https://github.com/Dr-TSNG/TwiFucker/blob/master/FEATURES.md
      </a>
      .
    </p>
    <h2 id="ni"><a href="#ni">🔚 最後に</a></h2>
    <p>
      root化を必要とせずにここまで出来るのはなかなかすごいと思います。
      昔root化して似たようなモジュールを導入していましたが、
      広告が表示されたら消すみたいな動作を行っていたせいかカクカクしていた記憶があります。
      よきTwitterライフが送れて大満足です。 皆様もよきTwitterライフを...。
    </p>
  </article>
</Post>
