<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="hajimeni"><a href="#hajimeni">✨はじめに</a></h1>
    <p>なぜこの記事を書いたかといいますと、MacbookにPop!OSを導入してVoidHack用の記事を書いていましたところ</p>
    <p>
      何故かバッククォート(`)が正常に打てなくていらいらしていたら実はキーボードレイアウトがUS配列だったのが原因でした。
    </p>
    <p>Linux関係は詳しくないのであくまで自分の備忘録として記事に残して置きます。</p>
    <h1 id="huan2-jing4"><a href="#huan2-jing4">💻環境</a></h1>
    <p>端末:Apple Inc. MacBookAir7,2</p>
    <p>OS:Pop!_OS 22.04 LTS x64</p>
    <p>X Window System:X11</p>
    <p>GNOME:42.5</p>
    <p>shell:zsh 5.8.1(gnome-terminal)</p>
    <h2 id="x-windows-systemwosuruniha"><a href="#x-windows-systemwosuruniha">X Windows Systemを確認するには...</a></h2>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token builtin class-name">echo</span> <span class="token environment constant">&#36;XDG_SESSION_TYPE</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token comment"># x11 ならばXorgで動作しています</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token comment"># waylandならばWaylandで動作しています</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token comment"># 今回はXorgのみで確認しています。</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h1 id="kbdoreiautowosuru"><a href="#kbdoreiautowosuru">キーボードレイアウトを変更する</a></h1>
    <p>ターミナルで下記コマンドを実行します。</p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">sudo</span> dpkg-reconfigure keyboard-configuration</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/terminal.png"
        alt="scrennshot-terminal"
        width="868"
        height="677" />
    </p>
    <p>そうすると下記のようなモデルの選択画面に遷移します。</p>
    <p>
      今回は
      <code class="inline-code-block">JISキーボード</code>
      を使用しているため
      <code class="inline-code-block">Apple Aluminium（JIS）</code>
      を選択しています。
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/model.png"
        alt="scrennshot-model-select"
        width="868"
        height="677" />
    </p>
    <p>
      次に進むと国設定に移動しますので
      <code class="inline-code-block">Japanese</code>
      を選択して進みます。
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/region.png"
        alt="scrennshot-region-select"
        width="868"
        height="677" />
    </p>
    <p>
      そうするとキーボードレイアウトを選択する画面に遷移するので
      <code class="inline-code-block">Japanese（Macintosh）</code>
      を選択します。
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/_layout.png"
        alt="scrennshot-layout-select"
        width="868"
        height="677" />
    </p>
    <p>これ以降はナショナル/ラテンモードの切り替え・一時切り替えを有効にするか質問されますが、</p>
    <p>
      いずれも切り替えなしを選択します。
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/change1.png"
        alt="scrennshot-choose-change1"
        width="868"
        height="677" />
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/change2.png"
        alt="scrennshot-choose-change2"
        width="868"
        height="677" />
    </p>
    <p>
      AltGrとして機能させるキーの設定:
      <code class="inline-code-block">キーボード配置のデフォルト</code>
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/alt_default.png"
        alt="scrennshot-altgr-select"
        width="868"
        height="677" />
    </p>
    <p>
      コンポーズキー:
      <code class="inline-code-block">コンポーズキーなし</code>
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/compose.png"
        alt="scrennshot-compose-select"
        width="868"
        height="677" />
    </p>
    <p>
      Xサーバーの強制に
      <kbd>Control</kbd>
      +
      <kbd>Alt</kbd>
      +
      <kbd>Backspace</kbd>
      を使うか:
      <code class="inline-code-block">いいえ</code>
      <ImgZoom
        src="/202304/linux-change-keyboardlayouts/assets/cab.png"
        alt="scrennshot-cab-select"
        width="868"
        height="677" />
    </p>
    <p>
      いいえを選択後は自動的にターミナルへ遷移し設定が終われば操作は終了です。 あとは
      <code class="inline-code-block">reboot</code>
      コマンド等を用いて端末を再起動しましょう。
    </p>
    <InfoBox statusType="danger">
      <p>
        再起動を行わないと
        <strong>設定が反映されないので必ず再起動を行いましょう。</strong>
      </p>
    </InfoBox>
    <h1 id="matome"><a href="#matome">まとめ</a></h1>
    <p>
      以上でキーボードレイアウトの変更が出来たかと思います。
      キーボード設定からキーボードレイアウトの表示を行ってキーボード刻印と相違がなければ問題ありません。
      またMozcの日本語切り替えは「かな」キーで切り替えが可能です。
    </p>
  </article>
</Post>
